# Generated by Django 3.0.5 on 2020-09-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200925_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.ManyToManyField(blank=True, default=None, related_name='genre', to='api.Title'),
        ),
    ]
